# Generated by Django 2.2 on 2019-04-26 05:20

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    replaces = [('NewsFeed', '0002_auto_20190426_0246'), ('NewsFeed', '0003_auto_20190426_0511')]

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('NewsFeed', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='school',
            name='owner',
            field=models.ForeignKey(help_text='학교의 뉴스피드를 관리하는 책임자로써 학교를 생성한 사용자', on_delete=django.db.models.deletion.PROTECT, to=settings.AUTH_USER_MODEL, verbose_name='관리자'),
        ),
        migrations.AlterField(
            model_name='school',
            name='region',
            field=models.CharField(choices=[('02', '서울특별시'), ('031', '경기도'), ('032', '인천광역시'), ('033', '강원도'), ('041', '충청남도'), ('042', '대전광역시'), ('043', '충청북도'), ('044', '세종특별자치시'), ('051', '부산광역시'), ('052', '울산광역시'), ('053', '대구광역시'), ('054', '경상북도'), ('055', '경상남도'), ('061', '전라남도'), ('062', '광주광역시'), ('063', '전라북도'), ('064', '제주특별자치도')], max_length=8, verbose_name='시/도'),
        ),
        migrations.CreateModel(
            name='Subscribe',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date_created', models.DateTimeField(auto_now_add=True, help_text='항목이 생성된 시점으로 자동 추가', verbose_name='생성일시')),
                ('date_modified', models.DateTimeField(auto_now=True, help_text='항목이 수정된 시점으로 수정시 자동 변경', verbose_name='수정일시')),
                ('date_subscribed', models.DateTimeField(auto_now_add=True, verbose_name='구독일시')),
                ('school', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='NewsFeed.School')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.AddField(
            model_name='school',
            name='subscribers',
            field=models.ManyToManyField(related_name='schools', through='NewsFeed.Subscribe', to=settings.AUTH_USER_MODEL, verbose_name='구독자들'),
        ),
        migrations.AlterField(
            model_name='school',
            name='name',
            field=models.CharField(db_index=True, max_length=256, verbose_name='학교명'),
        ),
    ]
