# Generated by Django 2.2 on 2019-04-26 05:38

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('NewsFeed', '0002_subscribe'),
    ]

    operations = [
        migrations.CreateModel(
            name='Article',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date_created', models.DateTimeField(auto_now_add=True, help_text='항목이 생성된 시점으로 자동 추가', verbose_name='생성일시')),
                ('date_modified', models.DateTimeField(auto_now=True, help_text='항목이 수정된 시점으로 수정시 자동 변경', verbose_name='수정일시')),
                ('content', models.TextField(verbose_name='글 내용')),
                ('owner', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='articles', to=settings.AUTH_USER_MODEL, verbose_name='작성자')),
                ('school', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='articles', to='NewsFeed.School', verbose_name='대상 학교')),
            ],
            options={
                'abstract': False,
            },
        ),
    ]
