# Generated by Django 2.2 on 2019-04-26 05:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('NewsFeed', '0002_auto_20190426_0246'),
    ]

    operations = [
        migrations.AlterField(
            model_name='school',
            name='name',
            field=models.CharField(db_index=True, max_length=256, verbose_name='학교명'),
        ),
    ]
