# Generated by Django 2.2 on 2019-04-26 13:50

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('NewsFeed', '0003_article'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='subscribe',
            name='date_created',
        ),
        migrations.RemoveField(
            model_name='subscribe',
            name='date_modified',
        ),
        migrations.CreateModel(
            name='Feed',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date_delivered', models.DateTimeField(auto_now_add=True, db_index=True, verbose_name='배달일시')),
                ('article', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='NewsFeed.Article', verbose_name='배달된 글')),
                ('receiver', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL, verbose_name='수신자')),
            ],
        ),
        migrations.AddField(
            model_name='article',
            name='receivers',
            field=models.ManyToManyField(related_name='received_articles', through='NewsFeed.Feed', to=settings.AUTH_USER_MODEL, verbose_name='수신자들'),
        ),
    ]
