# Generated by Django 2.2 on 2019-04-26 13:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('NewsFeed', '0004_newsfeed'),
    ]

    operations = [
        migrations.AlterField(
            model_name='feed',
            name='date_delivered',
            field=models.DateTimeField(auto_now_add=True, verbose_name='배달일시'),
        ),
    ]
